projects_folder: /u/apps
search_depth: 1
projects:
  rails:
    detection:
      folders:
        - app
        - db
        - public
        - vendor
    tasks:
      - label: Auto Testing
        command: autotest
      - label: MySQL
        command: mysql {project_name}_development
      - label: GiT 
        command: git remote show origin;git branch -a;git status;
      - label: Terminal
        command: growlnotify -m "It's kicked off and ready to go" {project_name}; say "{project_name} kicked off! (y'all have some fun);"
      - label: Restart Phusion
        command: touch tmp/restart.txt;mate README.textile app config lib db public spec test vendor/plugins
  erlang:
    detection:
      folders:
        - ebin
        - src
    tasks:
      - label: Erlang
        command: mate .; erl
      - label: Terminal
        command: say "{project_name} kicked off!"
  default:
    tasks:
      - label: HAL9000
        command: growlnotify -m "just what do you think you're doing dave?"; say "Nothing kicked off! - I will sing a song instead"; osascript -e 'say "oh This is a silly song silly song silly song this is the silliest song ive ever ever heard So why keep you listening listening listening while you are supposed to work to work to work to work" using "cellos"'
