projects_folder: /u/apps
search_depth: 1
projects:
  rails:
    detection:
      folders:
        - app
        - db
        - public
        - vendor
    tasks:
      - label: Auto Testing
        command: rake spec; autotest
      - label: Tail Development Log
        command: rake log:clear; tail -f log/development.log
      - label: Mongrel Server
        command: mate app config lib db public spec test vendor/plugins; mongrel_rails start   
      - label: GiT 
        command: git remote show origin;git branch -a;git status
      - label: MySQL
        command: mysql {project_name}_development
      - label: Terminal
        command: growlnotify -m "It's kicked off and ready to go" {project_name}; say "{project_name} kicked off! (y'all have some fun)"
  erlang:
    detection:
      folders:
        - ebin
        - src
    tasks:
      - label: Erlang
        command: mate .; erl
      - label: Terminal
        command: say "{project_name} kicked off!"
  default:
    tasks:
      - label: HAL9000
        command: growlnotify -m "just what do you think you're doing dave?"; say "Nothing kicked off! - I will sing a song instead, Daisy Daisy, Give me your answer do. I'm half crazy, All for the love of you."